version: '2'

services:
  server:
    build:
      context: ./backend/
    command: yarn start
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development

  client:
    build:
      context: ./client/
    command: yarn start
    depends_on:
      - server
    ports:
      - "3000:3000"